loop_params:
  date_start: '2021-01-01'
  date_end: '2022-01-15'
  symbol:
    - ACMUSDT
    - ALICEUSDT
    - BADGERUSDT
    - ADAUSDT
    - BATUSDT
    - AIONUSDT
    - ANTUSDT
    - 1INCHUSDT
    - AAVEUSDT
    - CAKEUSDT
    - BNBUSDT
    - ARDRUSDT
    - CKBUSDT
    - DEGOUSDT
    - ARPAUSDT
    - AUDUSDT
    - ADXUSDT
    - BTCUSDT
    - BTTUSDT
    - EOSUSDT
    - BALUSDT
    - AUTOUSDT
    - AGLDUSDT
    - ETCUSDT
    - ETHUSDT
    - CFXUSDT
    - EPSUSDT
    - AKROUSDT
    - BANDUSDT
    - BCHUSDT
    - LINAUSDT
    - ALGOUSDT
    - FETUSDT
    - BEAMUSDT
    - PERPUSDT
    - PUNDIXUSDT
    - HOTUSDT
    - ICXUSDT
    - BELUSDT
    - BLZUSDT
    - ALPACAUSDT
    - RAMPUSDT
    - TKOUSDT
    - BNTUSDT
    - IOTAUSDT
    - ALPHAUSDT
    - BTSUSDT
    - AMPUSDT
    - ANKRUSDT
    - LINKUSDT
    - LTCUSDT
    - BUSDUSDT
    - BARUSDT
    - BTGUSDT
    - FORTHUSDT
    - MIRUSDT
    - TLMUSDT
    - BAKEUSDT
    - BURGERUSDT
    - SLPUSDT
    - NEOUSDT
    - BZRXUSDT
    - NULSUSDT
    - ONGUSDT
    - CHRUSDT
    - CHZUSDT
    - ARUSDT
    - COMPUSDT
    - ONTUSDT
    - ASRUSDT
    - ATAUSDT
    - PAXUSDT
    - QTUMUSDT
    - COTIUSDT
    - CRVUSDT
    - ATMUSDT
    - TRXUSDT
    - CTSIUSDT
    - ATOMUSDT
    - AUCTIONUSDT
    - TUSDUSDT
    - CTXCUSDT
    - USDCUSDT
    - CVCUSDT
    - AUDIOUSDT
    - VETUSDT
    - DATAUSDT
    - WAVESUSDT
    - DCRUSDT
    - AVAUSDT
    - XLMUSDT
    - XRPUSDT
    - DENTUSDT
    - DGBUSDT
    - AVAXUSDT
    - DIAUSDT
    - AXSUSDT
    - ZILUSDT
    - DOCKUSDT
    - ZRXUSDT
    - DOTUSDT
    - DREPUSDT
    - EGLDUSDT
    - CELRUSDT
    - DASHUSDT
    - EURUSDT
    - ENJUSDT
    - FIOUSDT
    - FTTUSDT
    - FUNUSDT
    - FTMUSDT
    - GBPUSDT
    - GXSUSDT
    - BETAUSDT
    - COCOSUSDT
    - HBARUSDT
    - IOSTUSDT
    - COSUSDT
    - HIVEUSDT
    - IOTXUSDT
    - MATICUSDT
    - IRISUSDT
    - BNXUSDT
    - BONDUSDT
    - MITHUSDT
    - JSTUSDT
    - KAVAUSDT
    - BTCSTUSDT
    - NANOUSDT
    - KEYUSDT
    - DOGEUSDT
    - OMGUSDT
    - DUSKUSDT
    - KMDUSDT
    - KNCUSDT
    - ONEUSDT
    - KSMUSDT
    - GTOUSDT
    - LRCUSDT
    - LSKUSDT
    - LTOUSDT
    - C98USDT
    - TFUELUSDT
    - THETAUSDT
    - LUNAUSDT
    - MANAUSDT
    - MBLUSDT
    - CELOUSDT
    - MDTUSDT
    - MFTUSDT
    - CHESSUSDT
    - MKRUSDT
    - XMRUSDT
    - ZECUSDT
    - NBSUSDT
    - NKNUSDT
    - MTLUSDT
    - CITYUSDT
    - NMRUSDT
    - NPXSUSDT
    - OCEANUSDT
    - OGNUSDT
    - CLVUSDT
    - OXTUSDT
    - PAXGUSDT
    - PERLUSDT
    - RENUSDT
    - RVNUSDT
    - PNTUSDT
    - REPUSDT
    - STXUSDT
    - CTKUSDT
    - RLCUSDT
    - RSRUSDT
    - TOMOUSDT
    - RUNEUSDT
    - CVPUSDT
    - SANDUSDT
    - WANUSDT
    - WINUSDT
    - DARUSDT
    - SCUSDT
    - XTZUSDT
    - SNXUSDT
    - SOLUSDT
    - SRMUSDT
    - STMXUSDT
    - STORJUSDT
    - STPTUSDT
    - DEXEUSDT
    - DFUSDT
    - SUNUSDT
    - DNTUSDT
    - SUSHIUSDT
    - SXPUSDT
    - TCTUSDT
    - TRBUSDT
    - DODOUSDT
    - TROYUSDT
    - UMAUSDT
    - UNIUSDT
    - VITEUSDT
    - DYDXUSDT
    - ELFUSDT
    - ENSUSDT
    - ERNUSDT
    - FARMUSDT
    - FIDAUSDT
    - FILUSDT
    - FIROUSDT
    - FISUSDT
    - FLMUSDT
    - FLOWUSDT
    - FORUSDT
    - FRONTUSDT
    - GALAUSDT
    - GHSTUSDT
    - GNOUSDT
    - GRTUSDT
    - GTCUSDT
    - WRXUSDT
    - WTCUSDT
    - HARDUSDT
    - HNTUSDT
    - ICPUSDT
    - INJUSDT
    - VTHOUSDT
    - JUVUSDT
    - XZCUSDT
    - IDEXUSDT
    - ILVUSDT
    - LITUSDT
    - YFIUSDT
    - ZENUSDT
    - LPTUSDT
    - MASKUSDT
    - MDXUSDT
    - NEARUSDT
    - JASMYUSDT
    - OGUSDT
    - OMUSDT
    - ORNUSDT
    - KEEPUSDT
    - POLSUSDT
    - PONDUSDT
    - KLAYUSDT
    - PSGUSDT
    - REEFUSDT
    - KP3RUSDT
    - RIFUSDT
    - ROSEUSDT
    - LAZIOUSDT
    - SFPUSDT
    - SHIBUSDT
    - SKLUSDT
    - STRAXUSDT
    - SUSDUSDT
    - TRUUSDT
    - TWTUSDT
    - UNFIUSDT
    - UTKUSDT
    - XEMUSDT
    - MBOXUSDT
    - XVSUSDT
    - MINAUSDT
    - WINGUSDT
    - MLNUSDT
    - WNXMUSDT
    - MOVRUSDT
    - YFIIUSDT
    - NUUSDT
    - PHAUSDT
    - QNTUSDT
    - QUICKUSDT
    - RAYUSDT
    - TORNUSDT
    - TVKUSDT
    - XVGUSDT
    - REQUSDT
    - TRIBEUSDT
    - WAXPUSDT
    - POLYUSDT
    - PORTOUSDT
    - POWRUSDT
    - QIUSDT
    - RADUSDT
    - RAREUSDT
    - RGTUSDT
    - PLAUSDT
    - PYRUSDT
    - RNDRUSDT
    - ALCXUSDT
    - XECUSDT
    - USDPUSDT
    - VIDTUSDT
    - SYSUSDT
    - YGGUSDT
    - ANYUSDT
    - BICOUSDT
    - FLUXUSDT
    - MCUSDT
    - SANTOSUSDT
    - VGXUSDT
    - CVXUSDT
    - FXSUSDT
    - HIGHUSDT
    - JOEUSDT
    - OOKIUSDT
    - PEOPLEUSDT
    - SPELLUSDT
    - USTUSDT
    - VOXELUSDT
    - ACHUSDT
    - GLMRUSDT
    - IMXUSDT
    - ACAUSDT
    - ANCUSDT
    - API3USDT
    - BTTCUSDT
    - LOKAUSDT
    - SCRTUSDT
  minutes_to_trade_after_buy: 120
  avg_price_growth_per_step_limit_pct: 0.5
  min_price_growth_per_step_limit_pct: -18
  max_price_growth_per_step_limit_pct: 25
  back_check_period_length: 29
  stop_loss_pct_of_price_in: 5
  bid_pct_of_price_in: 20
  usd_balance: 100

